// Code generated by MockGen. DO NOT EDIT.
// Source: domain/crm/repository/repository.go
//
// Generated by this command:
//
//	mockgen -destination internal/mock/domain/crm/repository_mock.go -package crm -source domain/crm/repository/repository.go
//

// Package crm is a generated GoMock package.
package crm

import (
	context "context"
	reflect "reflect"

	entity "github.com/coze-dev/coze-studio/backend/domain/crm/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CountActiveContactsByCustomer mocks base method.
func (m *MockRepository) CountActiveContactsByCustomer(ctx context.Context, scope *entity.Scope, customerID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveContactsByCustomer", ctx, scope, customerID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveContactsByCustomer indicates an expected call of CountActiveContactsByCustomer.
func (mr *MockRepositoryMockRecorder) CountActiveContactsByCustomer(ctx, scope, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveContactsByCustomer", reflect.TypeOf((*MockRepository)(nil).CountActiveContactsByCustomer), ctx, scope, customerID)
}

// CountActiveOpportunitiesByCustomer mocks base method.
func (m *MockRepository) CountActiveOpportunitiesByCustomer(ctx context.Context, scope *entity.Scope, customerID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveOpportunitiesByCustomer", ctx, scope, customerID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveOpportunitiesByCustomer indicates an expected call of CountActiveOpportunitiesByCustomer.
func (mr *MockRepositoryMockRecorder) CountActiveOpportunitiesByCustomer(ctx, scope, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveOpportunitiesByCustomer", reflect.TypeOf((*MockRepository)(nil).CountActiveOpportunitiesByCustomer), ctx, scope, customerID)
}

// CreateContact mocks base method.
func (m *MockRepository) CreateContact(ctx context.Context, contact *entity.Contact) (*entity.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateContact", ctx, contact)
	ret0, _ := ret[0].(*entity.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateContact indicates an expected call of CreateContact.
func (mr *MockRepositoryMockRecorder) CreateContact(ctx, contact any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateContact", reflect.TypeOf((*MockRepository)(nil).CreateContact), ctx, contact)
}

// CreateCustomer mocks base method.
func (m *MockRepository) CreateCustomer(ctx context.Context, customer *entity.Customer) (*entity.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCustomer", ctx, customer)
	ret0, _ := ret[0].(*entity.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCustomer indicates an expected call of CreateCustomer.
func (mr *MockRepositoryMockRecorder) CreateCustomer(ctx, customer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCustomer", reflect.TypeOf((*MockRepository)(nil).CreateCustomer), ctx, customer)
}

// CreateFollowRecord mocks base method.
func (m *MockRepository) CreateFollowRecord(ctx context.Context, followRecord *entity.FollowRecord) (*entity.FollowRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFollowRecord", ctx, followRecord)
	ret0, _ := ret[0].(*entity.FollowRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFollowRecord indicates an expected call of CreateFollowRecord.
func (mr *MockRepositoryMockRecorder) CreateFollowRecord(ctx, followRecord any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFollowRecord", reflect.TypeOf((*MockRepository)(nil).CreateFollowRecord), ctx, followRecord)
}

// CreateOpportunity mocks base method.
func (m *MockRepository) CreateOpportunity(ctx context.Context, opportunity *entity.Opportunity) (*entity.Opportunity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOpportunity", ctx, opportunity)
	ret0, _ := ret[0].(*entity.Opportunity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOpportunity indicates an expected call of CreateOpportunity.
func (mr *MockRepositoryMockRecorder) CreateOpportunity(ctx, opportunity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOpportunity", reflect.TypeOf((*MockRepository)(nil).CreateOpportunity), ctx, opportunity)
}

// CreateProduct mocks base method.
func (m *MockRepository) CreateProduct(ctx context.Context, product *entity.Product) (*entity.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", ctx, product)
	ret0, _ := ret[0].(*entity.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockRepositoryMockRecorder) CreateProduct(ctx, product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockRepository)(nil).CreateProduct), ctx, product)
}

// CreateSalesOrder mocks base method.
func (m *MockRepository) CreateSalesOrder(ctx context.Context, salesOrder *entity.SalesOrder) (*entity.SalesOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSalesOrder", ctx, salesOrder)
	ret0, _ := ret[0].(*entity.SalesOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSalesOrder indicates an expected call of CreateSalesOrder.
func (mr *MockRepositoryMockRecorder) CreateSalesOrder(ctx, salesOrder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSalesOrder", reflect.TypeOf((*MockRepository)(nil).CreateSalesOrder), ctx, salesOrder)
}

// DeleteContact mocks base method.
func (m *MockRepository) DeleteContact(ctx context.Context, scope *entity.Scope, contactID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteContact", ctx, scope, contactID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteContact indicates an expected call of DeleteContact.
func (mr *MockRepositoryMockRecorder) DeleteContact(ctx, scope, contactID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteContact", reflect.TypeOf((*MockRepository)(nil).DeleteContact), ctx, scope, contactID)
}

// DeleteCustomer mocks base method.
func (m *MockRepository) DeleteCustomer(ctx context.Context, scope *entity.Scope, customerID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCustomer", ctx, scope, customerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCustomer indicates an expected call of DeleteCustomer.
func (mr *MockRepositoryMockRecorder) DeleteCustomer(ctx, scope, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCustomer", reflect.TypeOf((*MockRepository)(nil).DeleteCustomer), ctx, scope, customerID)
}

// DeleteFollowRecord mocks base method.
func (m *MockRepository) DeleteFollowRecord(ctx context.Context, scope *entity.Scope, followRecordID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFollowRecord", ctx, scope, followRecordID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFollowRecord indicates an expected call of DeleteFollowRecord.
func (mr *MockRepositoryMockRecorder) DeleteFollowRecord(ctx, scope, followRecordID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFollowRecord", reflect.TypeOf((*MockRepository)(nil).DeleteFollowRecord), ctx, scope, followRecordID)
}

// DeleteOpportunity mocks base method.
func (m *MockRepository) DeleteOpportunity(ctx context.Context, scope *entity.Scope, opportunityID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOpportunity", ctx, scope, opportunityID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOpportunity indicates an expected call of DeleteOpportunity.
func (mr *MockRepositoryMockRecorder) DeleteOpportunity(ctx, scope, opportunityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOpportunity", reflect.TypeOf((*MockRepository)(nil).DeleteOpportunity), ctx, scope, opportunityID)
}

// DeleteProduct mocks base method.
func (m *MockRepository) DeleteProduct(ctx context.Context, scope *entity.Scope, productID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProduct", ctx, scope, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProduct indicates an expected call of DeleteProduct.
func (mr *MockRepositoryMockRecorder) DeleteProduct(ctx, scope, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockRepository)(nil).DeleteProduct), ctx, scope, productID)
}

// DeleteSalesOrder mocks base method.
func (m *MockRepository) DeleteSalesOrder(ctx context.Context, scope *entity.Scope, salesOrderID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSalesOrder", ctx, scope, salesOrderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSalesOrder indicates an expected call of DeleteSalesOrder.
func (mr *MockRepositoryMockRecorder) DeleteSalesOrder(ctx, scope, salesOrderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSalesOrder", reflect.TypeOf((*MockRepository)(nil).DeleteSalesOrder), ctx, scope, salesOrderID)
}

// GetContact mocks base method.
func (m *MockRepository) GetContact(ctx context.Context, scope *entity.Scope, contactID int64) (*entity.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContact", ctx, scope, contactID)
	ret0, _ := ret[0].(*entity.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContact indicates an expected call of GetContact.
func (mr *MockRepositoryMockRecorder) GetContact(ctx, scope, contactID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContact", reflect.TypeOf((*MockRepository)(nil).GetContact), ctx, scope, contactID)
}

// GetContactByID mocks base method.
func (m *MockRepository) GetContactByID(ctx context.Context, contactID int64) (*entity.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContactByID", ctx, contactID)
	ret0, _ := ret[0].(*entity.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContactByID indicates an expected call of GetContactByID.
func (mr *MockRepositoryMockRecorder) GetContactByID(ctx, contactID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContactByID", reflect.TypeOf((*MockRepository)(nil).GetContactByID), ctx, contactID)
}

// GetCustomer mocks base method.
func (m *MockRepository) GetCustomer(ctx context.Context, scope *entity.Scope, customerID int64) (*entity.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomer", ctx, scope, customerID)
	ret0, _ := ret[0].(*entity.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomer indicates an expected call of GetCustomer.
func (mr *MockRepositoryMockRecorder) GetCustomer(ctx, scope, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomer", reflect.TypeOf((*MockRepository)(nil).GetCustomer), ctx, scope, customerID)
}

// GetCustomerByID mocks base method.
func (m *MockRepository) GetCustomerByID(ctx context.Context, customerID int64) (*entity.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomerByID", ctx, customerID)
	ret0, _ := ret[0].(*entity.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomerByID indicates an expected call of GetCustomerByID.
func (mr *MockRepositoryMockRecorder) GetCustomerByID(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomerByID", reflect.TypeOf((*MockRepository)(nil).GetCustomerByID), ctx, customerID)
}

// GetFollowRecord mocks base method.
func (m *MockRepository) GetFollowRecord(ctx context.Context, scope *entity.Scope, followRecordID int64) (*entity.FollowRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowRecord", ctx, scope, followRecordID)
	ret0, _ := ret[0].(*entity.FollowRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowRecord indicates an expected call of GetFollowRecord.
func (mr *MockRepositoryMockRecorder) GetFollowRecord(ctx, scope, followRecordID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowRecord", reflect.TypeOf((*MockRepository)(nil).GetFollowRecord), ctx, scope, followRecordID)
}

// GetFollowRecordByID mocks base method.
func (m *MockRepository) GetFollowRecordByID(ctx context.Context, followRecordID int64) (*entity.FollowRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowRecordByID", ctx, followRecordID)
	ret0, _ := ret[0].(*entity.FollowRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowRecordByID indicates an expected call of GetFollowRecordByID.
func (mr *MockRepositoryMockRecorder) GetFollowRecordByID(ctx, followRecordID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowRecordByID", reflect.TypeOf((*MockRepository)(nil).GetFollowRecordByID), ctx, followRecordID)
}

// GetOpportunity mocks base method.
func (m *MockRepository) GetOpportunity(ctx context.Context, scope *entity.Scope, opportunityID int64) (*entity.Opportunity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOpportunity", ctx, scope, opportunityID)
	ret0, _ := ret[0].(*entity.Opportunity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOpportunity indicates an expected call of GetOpportunity.
func (mr *MockRepositoryMockRecorder) GetOpportunity(ctx, scope, opportunityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOpportunity", reflect.TypeOf((*MockRepository)(nil).GetOpportunity), ctx, scope, opportunityID)
}

// GetOpportunityByID mocks base method.
func (m *MockRepository) GetOpportunityByID(ctx context.Context, opportunityID int64) (*entity.Opportunity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOpportunityByID", ctx, opportunityID)
	ret0, _ := ret[0].(*entity.Opportunity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOpportunityByID indicates an expected call of GetOpportunityByID.
func (mr *MockRepositoryMockRecorder) GetOpportunityByID(ctx, opportunityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOpportunityByID", reflect.TypeOf((*MockRepository)(nil).GetOpportunityByID), ctx, opportunityID)
}

// GetProduct mocks base method.
func (m *MockRepository) GetProduct(ctx context.Context, scope *entity.Scope, productID int64) (*entity.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProduct", ctx, scope, productID)
	ret0, _ := ret[0].(*entity.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProduct indicates an expected call of GetProduct.
func (mr *MockRepositoryMockRecorder) GetProduct(ctx, scope, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProduct", reflect.TypeOf((*MockRepository)(nil).GetProduct), ctx, scope, productID)
}

// GetProductByID mocks base method.
func (m *MockRepository) GetProductByID(ctx context.Context, productID int64) (*entity.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductByID", ctx, productID)
	ret0, _ := ret[0].(*entity.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductByID indicates an expected call of GetProductByID.
func (mr *MockRepositoryMockRecorder) GetProductByID(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductByID", reflect.TypeOf((*MockRepository)(nil).GetProductByID), ctx, productID)
}

// GetSalesOrder mocks base method.
func (m *MockRepository) GetSalesOrder(ctx context.Context, scope *entity.Scope, salesOrderID int64) (*entity.SalesOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSalesOrder", ctx, scope, salesOrderID)
	ret0, _ := ret[0].(*entity.SalesOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSalesOrder indicates an expected call of GetSalesOrder.
func (mr *MockRepositoryMockRecorder) GetSalesOrder(ctx, scope, salesOrderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSalesOrder", reflect.TypeOf((*MockRepository)(nil).GetSalesOrder), ctx, scope, salesOrderID)
}

// GetSalesOrderByID mocks base method.
func (m *MockRepository) GetSalesOrderByID(ctx context.Context, salesOrderID int64) (*entity.SalesOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSalesOrderByID", ctx, salesOrderID)
	ret0, _ := ret[0].(*entity.SalesOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSalesOrderByID indicates an expected call of GetSalesOrderByID.
func (mr *MockRepositoryMockRecorder) GetSalesOrderByID(ctx, salesOrderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSalesOrderByID", reflect.TypeOf((*MockRepository)(nil).GetSalesOrderByID), ctx, salesOrderID)
}

// GetDashboardOverview mocks base method.
func (m *MockRepository) GetDashboardOverview(ctx context.Context, scope *entity.Scope) (*entity.DashboardOverview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDashboardOverview", ctx, scope)
	ret0, _ := ret[0].(*entity.DashboardOverview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDashboardOverview indicates an expected call of GetDashboardOverview.
func (mr *MockRepositoryMockRecorder) GetDashboardOverview(ctx, scope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDashboardOverview", reflect.TypeOf((*MockRepository)(nil).GetDashboardOverview), ctx, scope)
}

// ListContacts mocks base method.
func (m *MockRepository) ListContacts(ctx context.Context, filter *entity.ContactFilter) ([]*entity.Contact, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListContacts", ctx, filter)
	ret0, _ := ret[0].([]*entity.Contact)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListContacts indicates an expected call of ListContacts.
func (mr *MockRepositoryMockRecorder) ListContacts(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListContacts", reflect.TypeOf((*MockRepository)(nil).ListContacts), ctx, filter)
}

// ListCustomers mocks base method.
func (m *MockRepository) ListCustomers(ctx context.Context, filter *entity.CustomerFilter) ([]*entity.Customer, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCustomers", ctx, filter)
	ret0, _ := ret[0].([]*entity.Customer)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListCustomers indicates an expected call of ListCustomers.
func (mr *MockRepositoryMockRecorder) ListCustomers(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCustomers", reflect.TypeOf((*MockRepository)(nil).ListCustomers), ctx, filter)
}

// ListFollowRecords mocks base method.
func (m *MockRepository) ListFollowRecords(ctx context.Context, filter *entity.FollowRecordFilter) ([]*entity.FollowRecord, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFollowRecords", ctx, filter)
	ret0, _ := ret[0].([]*entity.FollowRecord)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListFollowRecords indicates an expected call of ListFollowRecords.
func (mr *MockRepositoryMockRecorder) ListFollowRecords(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFollowRecords", reflect.TypeOf((*MockRepository)(nil).ListFollowRecords), ctx, filter)
}

// ListOpportunities mocks base method.
func (m *MockRepository) ListOpportunities(ctx context.Context, filter *entity.OpportunityFilter) ([]*entity.Opportunity, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOpportunities", ctx, filter)
	ret0, _ := ret[0].([]*entity.Opportunity)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListOpportunities indicates an expected call of ListOpportunities.
func (mr *MockRepositoryMockRecorder) ListOpportunities(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOpportunities", reflect.TypeOf((*MockRepository)(nil).ListOpportunities), ctx, filter)
}

// ListProducts mocks base method.
func (m *MockRepository) ListProducts(ctx context.Context, filter *entity.ProductFilter) ([]*entity.Product, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProducts", ctx, filter)
	ret0, _ := ret[0].([]*entity.Product)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListProducts indicates an expected call of ListProducts.
func (mr *MockRepositoryMockRecorder) ListProducts(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProducts", reflect.TypeOf((*MockRepository)(nil).ListProducts), ctx, filter)
}

// ListSalesOrders mocks base method.
func (m *MockRepository) ListSalesOrders(ctx context.Context, filter *entity.SalesOrderFilter) ([]*entity.SalesOrder, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSalesOrders", ctx, filter)
	ret0, _ := ret[0].([]*entity.SalesOrder)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListSalesOrders indicates an expected call of ListSalesOrders.
func (mr *MockRepositoryMockRecorder) ListSalesOrders(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSalesOrders", reflect.TypeOf((*MockRepository)(nil).ListSalesOrders), ctx, filter)
}

// UpdateContact mocks base method.
func (m *MockRepository) UpdateContact(ctx context.Context, contact *entity.Contact) (*entity.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateContact", ctx, contact)
	ret0, _ := ret[0].(*entity.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateContact indicates an expected call of UpdateContact.
func (mr *MockRepositoryMockRecorder) UpdateContact(ctx, contact any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateContact", reflect.TypeOf((*MockRepository)(nil).UpdateContact), ctx, contact)
}

// UpdateCustomer mocks base method.
func (m *MockRepository) UpdateCustomer(ctx context.Context, customer *entity.Customer) (*entity.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCustomer", ctx, customer)
	ret0, _ := ret[0].(*entity.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCustomer indicates an expected call of UpdateCustomer.
func (mr *MockRepositoryMockRecorder) UpdateCustomer(ctx, customer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCustomer", reflect.TypeOf((*MockRepository)(nil).UpdateCustomer), ctx, customer)
}

// UpdateFollowRecord mocks base method.
func (m *MockRepository) UpdateFollowRecord(ctx context.Context, followRecord *entity.FollowRecord) (*entity.FollowRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFollowRecord", ctx, followRecord)
	ret0, _ := ret[0].(*entity.FollowRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateFollowRecord indicates an expected call of UpdateFollowRecord.
func (mr *MockRepositoryMockRecorder) UpdateFollowRecord(ctx, followRecord any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFollowRecord", reflect.TypeOf((*MockRepository)(nil).UpdateFollowRecord), ctx, followRecord)
}

// UpdateOpportunity mocks base method.
func (m *MockRepository) UpdateOpportunity(ctx context.Context, opportunity *entity.Opportunity) (*entity.Opportunity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOpportunity", ctx, opportunity)
	ret0, _ := ret[0].(*entity.Opportunity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOpportunity indicates an expected call of UpdateOpportunity.
func (mr *MockRepositoryMockRecorder) UpdateOpportunity(ctx, opportunity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOpportunity", reflect.TypeOf((*MockRepository)(nil).UpdateOpportunity), ctx, opportunity)
}

// UpdateProduct mocks base method.
func (m *MockRepository) UpdateProduct(ctx context.Context, product *entity.Product) (*entity.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProduct", ctx, product)
	ret0, _ := ret[0].(*entity.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockRepositoryMockRecorder) UpdateProduct(ctx, product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockRepository)(nil).UpdateProduct), ctx, product)
}

// UpdateSalesOrder mocks base method.
func (m *MockRepository) UpdateSalesOrder(ctx context.Context, salesOrder *entity.SalesOrder) (*entity.SalesOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSalesOrder", ctx, salesOrder)
	ret0, _ := ret[0].(*entity.SalesOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSalesOrder indicates an expected call of UpdateSalesOrder.
func (mr *MockRepositoryMockRecorder) UpdateSalesOrder(ctx, salesOrder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSalesOrder", reflect.TypeOf((*MockRepository)(nil).UpdateSalesOrder), ctx, salesOrder)
}

// MockCustomerRepository is a mock of CustomerRepository interface.
type MockCustomerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerRepositoryMockRecorder
	isgomock struct{}
}

// MockCustomerRepositoryMockRecorder is the mock recorder for MockCustomerRepository.
type MockCustomerRepositoryMockRecorder struct {
	mock *MockCustomerRepository
}

// NewMockCustomerRepository creates a new mock instance.
func NewMockCustomerRepository(ctrl *gomock.Controller) *MockCustomerRepository {
	mock := &MockCustomerRepository{ctrl: ctrl}
	mock.recorder = &MockCustomerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerRepository) EXPECT() *MockCustomerRepositoryMockRecorder {
	return m.recorder
}

// CountActiveContactsByCustomer mocks base method.
func (m *MockCustomerRepository) CountActiveContactsByCustomer(ctx context.Context, scope *entity.Scope, customerID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveContactsByCustomer", ctx, scope, customerID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveContactsByCustomer indicates an expected call of CountActiveContactsByCustomer.
func (mr *MockCustomerRepositoryMockRecorder) CountActiveContactsByCustomer(ctx, scope, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveContactsByCustomer", reflect.TypeOf((*MockCustomerRepository)(nil).CountActiveContactsByCustomer), ctx, scope, customerID)
}

// CountActiveOpportunitiesByCustomer mocks base method.
func (m *MockCustomerRepository) CountActiveOpportunitiesByCustomer(ctx context.Context, scope *entity.Scope, customerID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveOpportunitiesByCustomer", ctx, scope, customerID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveOpportunitiesByCustomer indicates an expected call of CountActiveOpportunitiesByCustomer.
func (mr *MockCustomerRepositoryMockRecorder) CountActiveOpportunitiesByCustomer(ctx, scope, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveOpportunitiesByCustomer", reflect.TypeOf((*MockCustomerRepository)(nil).CountActiveOpportunitiesByCustomer), ctx, scope, customerID)
}

// CreateCustomer mocks base method.
func (m *MockCustomerRepository) CreateCustomer(ctx context.Context, customer *entity.Customer) (*entity.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCustomer", ctx, customer)
	ret0, _ := ret[0].(*entity.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCustomer indicates an expected call of CreateCustomer.
func (mr *MockCustomerRepositoryMockRecorder) CreateCustomer(ctx, customer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCustomer", reflect.TypeOf((*MockCustomerRepository)(nil).CreateCustomer), ctx, customer)
}

// DeleteCustomer mocks base method.
func (m *MockCustomerRepository) DeleteCustomer(ctx context.Context, scope *entity.Scope, customerID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCustomer", ctx, scope, customerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCustomer indicates an expected call of DeleteCustomer.
func (mr *MockCustomerRepositoryMockRecorder) DeleteCustomer(ctx, scope, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCustomer", reflect.TypeOf((*MockCustomerRepository)(nil).DeleteCustomer), ctx, scope, customerID)
}

// GetCustomer mocks base method.
func (m *MockCustomerRepository) GetCustomer(ctx context.Context, scope *entity.Scope, customerID int64) (*entity.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomer", ctx, scope, customerID)
	ret0, _ := ret[0].(*entity.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomer indicates an expected call of GetCustomer.
func (mr *MockCustomerRepositoryMockRecorder) GetCustomer(ctx, scope, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomer", reflect.TypeOf((*MockCustomerRepository)(nil).GetCustomer), ctx, scope, customerID)
}

// GetCustomerByID mocks base method.
func (m *MockCustomerRepository) GetCustomerByID(ctx context.Context, customerID int64) (*entity.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomerByID", ctx, customerID)
	ret0, _ := ret[0].(*entity.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomerByID indicates an expected call of GetCustomerByID.
func (mr *MockCustomerRepositoryMockRecorder) GetCustomerByID(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomerByID", reflect.TypeOf((*MockCustomerRepository)(nil).GetCustomerByID), ctx, customerID)
}

// ListCustomers mocks base method.
func (m *MockCustomerRepository) ListCustomers(ctx context.Context, filter *entity.CustomerFilter) ([]*entity.Customer, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCustomers", ctx, filter)
	ret0, _ := ret[0].([]*entity.Customer)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListCustomers indicates an expected call of ListCustomers.
func (mr *MockCustomerRepositoryMockRecorder) ListCustomers(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCustomers", reflect.TypeOf((*MockCustomerRepository)(nil).ListCustomers), ctx, filter)
}

// UpdateCustomer mocks base method.
func (m *MockCustomerRepository) UpdateCustomer(ctx context.Context, customer *entity.Customer) (*entity.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCustomer", ctx, customer)
	ret0, _ := ret[0].(*entity.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCustomer indicates an expected call of UpdateCustomer.
func (mr *MockCustomerRepositoryMockRecorder) UpdateCustomer(ctx, customer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCustomer", reflect.TypeOf((*MockCustomerRepository)(nil).UpdateCustomer), ctx, customer)
}

// MockContactRepository is a mock of ContactRepository interface.
type MockContactRepository struct {
	ctrl     *gomock.Controller
	recorder *MockContactRepositoryMockRecorder
	isgomock struct{}
}

// MockContactRepositoryMockRecorder is the mock recorder for MockContactRepository.
type MockContactRepositoryMockRecorder struct {
	mock *MockContactRepository
}

// NewMockContactRepository creates a new mock instance.
func NewMockContactRepository(ctrl *gomock.Controller) *MockContactRepository {
	mock := &MockContactRepository{ctrl: ctrl}
	mock.recorder = &MockContactRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContactRepository) EXPECT() *MockContactRepositoryMockRecorder {
	return m.recorder
}

// CreateContact mocks base method.
func (m *MockContactRepository) CreateContact(ctx context.Context, contact *entity.Contact) (*entity.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateContact", ctx, contact)
	ret0, _ := ret[0].(*entity.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateContact indicates an expected call of CreateContact.
func (mr *MockContactRepositoryMockRecorder) CreateContact(ctx, contact any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateContact", reflect.TypeOf((*MockContactRepository)(nil).CreateContact), ctx, contact)
}

// DeleteContact mocks base method.
func (m *MockContactRepository) DeleteContact(ctx context.Context, scope *entity.Scope, contactID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteContact", ctx, scope, contactID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteContact indicates an expected call of DeleteContact.
func (mr *MockContactRepositoryMockRecorder) DeleteContact(ctx, scope, contactID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteContact", reflect.TypeOf((*MockContactRepository)(nil).DeleteContact), ctx, scope, contactID)
}

// GetContact mocks base method.
func (m *MockContactRepository) GetContact(ctx context.Context, scope *entity.Scope, contactID int64) (*entity.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContact", ctx, scope, contactID)
	ret0, _ := ret[0].(*entity.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContact indicates an expected call of GetContact.
func (mr *MockContactRepositoryMockRecorder) GetContact(ctx, scope, contactID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContact", reflect.TypeOf((*MockContactRepository)(nil).GetContact), ctx, scope, contactID)
}

// GetContactByID mocks base method.
func (m *MockContactRepository) GetContactByID(ctx context.Context, contactID int64) (*entity.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContactByID", ctx, contactID)
	ret0, _ := ret[0].(*entity.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContactByID indicates an expected call of GetContactByID.
func (mr *MockContactRepositoryMockRecorder) GetContactByID(ctx, contactID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContactByID", reflect.TypeOf((*MockContactRepository)(nil).GetContactByID), ctx, contactID)
}

// ListContacts mocks base method.
func (m *MockContactRepository) ListContacts(ctx context.Context, filter *entity.ContactFilter) ([]*entity.Contact, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListContacts", ctx, filter)
	ret0, _ := ret[0].([]*entity.Contact)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListContacts indicates an expected call of ListContacts.
func (mr *MockContactRepositoryMockRecorder) ListContacts(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListContacts", reflect.TypeOf((*MockContactRepository)(nil).ListContacts), ctx, filter)
}

// UpdateContact mocks base method.
func (m *MockContactRepository) UpdateContact(ctx context.Context, contact *entity.Contact) (*entity.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateContact", ctx, contact)
	ret0, _ := ret[0].(*entity.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateContact indicates an expected call of UpdateContact.
func (mr *MockContactRepositoryMockRecorder) UpdateContact(ctx, contact any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateContact", reflect.TypeOf((*MockContactRepository)(nil).UpdateContact), ctx, contact)
}

// MockOpportunityRepository is a mock of OpportunityRepository interface.
type MockOpportunityRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOpportunityRepositoryMockRecorder
	isgomock struct{}
}

// MockOpportunityRepositoryMockRecorder is the mock recorder for MockOpportunityRepository.
type MockOpportunityRepositoryMockRecorder struct {
	mock *MockOpportunityRepository
}

// NewMockOpportunityRepository creates a new mock instance.
func NewMockOpportunityRepository(ctrl *gomock.Controller) *MockOpportunityRepository {
	mock := &MockOpportunityRepository{ctrl: ctrl}
	mock.recorder = &MockOpportunityRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOpportunityRepository) EXPECT() *MockOpportunityRepositoryMockRecorder {
	return m.recorder
}

// CreateOpportunity mocks base method.
func (m *MockOpportunityRepository) CreateOpportunity(ctx context.Context, opportunity *entity.Opportunity) (*entity.Opportunity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOpportunity", ctx, opportunity)
	ret0, _ := ret[0].(*entity.Opportunity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOpportunity indicates an expected call of CreateOpportunity.
func (mr *MockOpportunityRepositoryMockRecorder) CreateOpportunity(ctx, opportunity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOpportunity", reflect.TypeOf((*MockOpportunityRepository)(nil).CreateOpportunity), ctx, opportunity)
}

// DeleteOpportunity mocks base method.
func (m *MockOpportunityRepository) DeleteOpportunity(ctx context.Context, scope *entity.Scope, opportunityID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOpportunity", ctx, scope, opportunityID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOpportunity indicates an expected call of DeleteOpportunity.
func (mr *MockOpportunityRepositoryMockRecorder) DeleteOpportunity(ctx, scope, opportunityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOpportunity", reflect.TypeOf((*MockOpportunityRepository)(nil).DeleteOpportunity), ctx, scope, opportunityID)
}

// GetOpportunity mocks base method.
func (m *MockOpportunityRepository) GetOpportunity(ctx context.Context, scope *entity.Scope, opportunityID int64) (*entity.Opportunity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOpportunity", ctx, scope, opportunityID)
	ret0, _ := ret[0].(*entity.Opportunity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOpportunity indicates an expected call of GetOpportunity.
func (mr *MockOpportunityRepositoryMockRecorder) GetOpportunity(ctx, scope, opportunityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOpportunity", reflect.TypeOf((*MockOpportunityRepository)(nil).GetOpportunity), ctx, scope, opportunityID)
}

// GetOpportunityByID mocks base method.
func (m *MockOpportunityRepository) GetOpportunityByID(ctx context.Context, opportunityID int64) (*entity.Opportunity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOpportunityByID", ctx, opportunityID)
	ret0, _ := ret[0].(*entity.Opportunity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOpportunityByID indicates an expected call of GetOpportunityByID.
func (mr *MockOpportunityRepositoryMockRecorder) GetOpportunityByID(ctx, opportunityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOpportunityByID", reflect.TypeOf((*MockOpportunityRepository)(nil).GetOpportunityByID), ctx, opportunityID)
}

// ListOpportunities mocks base method.
func (m *MockOpportunityRepository) ListOpportunities(ctx context.Context, filter *entity.OpportunityFilter) ([]*entity.Opportunity, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOpportunities", ctx, filter)
	ret0, _ := ret[0].([]*entity.Opportunity)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListOpportunities indicates an expected call of ListOpportunities.
func (mr *MockOpportunityRepositoryMockRecorder) ListOpportunities(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOpportunities", reflect.TypeOf((*MockOpportunityRepository)(nil).ListOpportunities), ctx, filter)
}

// UpdateOpportunity mocks base method.
func (m *MockOpportunityRepository) UpdateOpportunity(ctx context.Context, opportunity *entity.Opportunity) (*entity.Opportunity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOpportunity", ctx, opportunity)
	ret0, _ := ret[0].(*entity.Opportunity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOpportunity indicates an expected call of UpdateOpportunity.
func (mr *MockOpportunityRepositoryMockRecorder) UpdateOpportunity(ctx, opportunity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOpportunity", reflect.TypeOf((*MockOpportunityRepository)(nil).UpdateOpportunity), ctx, opportunity)
}

// MockFollowRecordRepository is a mock of FollowRecordRepository interface.
type MockFollowRecordRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFollowRecordRepositoryMockRecorder
	isgomock struct{}
}

// MockFollowRecordRepositoryMockRecorder is the mock recorder for MockFollowRecordRepository.
type MockFollowRecordRepositoryMockRecorder struct {
	mock *MockFollowRecordRepository
}

// NewMockFollowRecordRepository creates a new mock instance.
func NewMockFollowRecordRepository(ctrl *gomock.Controller) *MockFollowRecordRepository {
	mock := &MockFollowRecordRepository{ctrl: ctrl}
	mock.recorder = &MockFollowRecordRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFollowRecordRepository) EXPECT() *MockFollowRecordRepositoryMockRecorder {
	return m.recorder
}

// CreateFollowRecord mocks base method.
func (m *MockFollowRecordRepository) CreateFollowRecord(ctx context.Context, followRecord *entity.FollowRecord) (*entity.FollowRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFollowRecord", ctx, followRecord)
	ret0, _ := ret[0].(*entity.FollowRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFollowRecord indicates an expected call of CreateFollowRecord.
func (mr *MockFollowRecordRepositoryMockRecorder) CreateFollowRecord(ctx, followRecord any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFollowRecord", reflect.TypeOf((*MockFollowRecordRepository)(nil).CreateFollowRecord), ctx, followRecord)
}

// DeleteFollowRecord mocks base method.
func (m *MockFollowRecordRepository) DeleteFollowRecord(ctx context.Context, scope *entity.Scope, followRecordID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFollowRecord", ctx, scope, followRecordID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFollowRecord indicates an expected call of DeleteFollowRecord.
func (mr *MockFollowRecordRepositoryMockRecorder) DeleteFollowRecord(ctx, scope, followRecordID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFollowRecord", reflect.TypeOf((*MockFollowRecordRepository)(nil).DeleteFollowRecord), ctx, scope, followRecordID)
}

// GetFollowRecord mocks base method.
func (m *MockFollowRecordRepository) GetFollowRecord(ctx context.Context, scope *entity.Scope, followRecordID int64) (*entity.FollowRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowRecord", ctx, scope, followRecordID)
	ret0, _ := ret[0].(*entity.FollowRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowRecord indicates an expected call of GetFollowRecord.
func (mr *MockFollowRecordRepositoryMockRecorder) GetFollowRecord(ctx, scope, followRecordID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowRecord", reflect.TypeOf((*MockFollowRecordRepository)(nil).GetFollowRecord), ctx, scope, followRecordID)
}

// GetFollowRecordByID mocks base method.
func (m *MockFollowRecordRepository) GetFollowRecordByID(ctx context.Context, followRecordID int64) (*entity.FollowRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowRecordByID", ctx, followRecordID)
	ret0, _ := ret[0].(*entity.FollowRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowRecordByID indicates an expected call of GetFollowRecordByID.
func (mr *MockFollowRecordRepositoryMockRecorder) GetFollowRecordByID(ctx, followRecordID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowRecordByID", reflect.TypeOf((*MockFollowRecordRepository)(nil).GetFollowRecordByID), ctx, followRecordID)
}

// ListFollowRecords mocks base method.
func (m *MockFollowRecordRepository) ListFollowRecords(ctx context.Context, filter *entity.FollowRecordFilter) ([]*entity.FollowRecord, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFollowRecords", ctx, filter)
	ret0, _ := ret[0].([]*entity.FollowRecord)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListFollowRecords indicates an expected call of ListFollowRecords.
func (mr *MockFollowRecordRepositoryMockRecorder) ListFollowRecords(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFollowRecords", reflect.TypeOf((*MockFollowRecordRepository)(nil).ListFollowRecords), ctx, filter)
}

// UpdateFollowRecord mocks base method.
func (m *MockFollowRecordRepository) UpdateFollowRecord(ctx context.Context, followRecord *entity.FollowRecord) (*entity.FollowRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFollowRecord", ctx, followRecord)
	ret0, _ := ret[0].(*entity.FollowRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateFollowRecord indicates an expected call of UpdateFollowRecord.
func (mr *MockFollowRecordRepositoryMockRecorder) UpdateFollowRecord(ctx, followRecord any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFollowRecord", reflect.TypeOf((*MockFollowRecordRepository)(nil).UpdateFollowRecord), ctx, followRecord)
}

// MockProductRepository is a mock of ProductRepository interface.
type MockProductRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProductRepositoryMockRecorder
	isgomock struct{}
}

// MockProductRepositoryMockRecorder is the mock recorder for MockProductRepository.
type MockProductRepositoryMockRecorder struct {
	mock *MockProductRepository
}

// NewMockProductRepository creates a new mock instance.
func NewMockProductRepository(ctrl *gomock.Controller) *MockProductRepository {
	mock := &MockProductRepository{ctrl: ctrl}
	mock.recorder = &MockProductRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductRepository) EXPECT() *MockProductRepositoryMockRecorder {
	return m.recorder
}

// CreateProduct mocks base method.
func (m *MockProductRepository) CreateProduct(ctx context.Context, product *entity.Product) (*entity.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", ctx, product)
	ret0, _ := ret[0].(*entity.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockProductRepositoryMockRecorder) CreateProduct(ctx, product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockProductRepository)(nil).CreateProduct), ctx, product)
}

// DeleteProduct mocks base method.
func (m *MockProductRepository) DeleteProduct(ctx context.Context, scope *entity.Scope, productID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProduct", ctx, scope, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProduct indicates an expected call of DeleteProduct.
func (mr *MockProductRepositoryMockRecorder) DeleteProduct(ctx, scope, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockProductRepository)(nil).DeleteProduct), ctx, scope, productID)
}

// GetProduct mocks base method.
func (m *MockProductRepository) GetProduct(ctx context.Context, scope *entity.Scope, productID int64) (*entity.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProduct", ctx, scope, productID)
	ret0, _ := ret[0].(*entity.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProduct indicates an expected call of GetProduct.
func (mr *MockProductRepositoryMockRecorder) GetProduct(ctx, scope, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProduct", reflect.TypeOf((*MockProductRepository)(nil).GetProduct), ctx, scope, productID)
}

// GetProductByID mocks base method.
func (m *MockProductRepository) GetProductByID(ctx context.Context, productID int64) (*entity.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductByID", ctx, productID)
	ret0, _ := ret[0].(*entity.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductByID indicates an expected call of GetProductByID.
func (mr *MockProductRepositoryMockRecorder) GetProductByID(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductByID", reflect.TypeOf((*MockProductRepository)(nil).GetProductByID), ctx, productID)
}

// ListProducts mocks base method.
func (m *MockProductRepository) ListProducts(ctx context.Context, filter *entity.ProductFilter) ([]*entity.Product, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProducts", ctx, filter)
	ret0, _ := ret[0].([]*entity.Product)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListProducts indicates an expected call of ListProducts.
func (mr *MockProductRepositoryMockRecorder) ListProducts(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProducts", reflect.TypeOf((*MockProductRepository)(nil).ListProducts), ctx, filter)
}

// UpdateProduct mocks base method.
func (m *MockProductRepository) UpdateProduct(ctx context.Context, product *entity.Product) (*entity.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProduct", ctx, product)
	ret0, _ := ret[0].(*entity.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockProductRepositoryMockRecorder) UpdateProduct(ctx, product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockProductRepository)(nil).UpdateProduct), ctx, product)
}

// MockSalesOrderRepository is a mock of SalesOrderRepository interface.
type MockSalesOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSalesOrderRepositoryMockRecorder
	isgomock struct{}
}

// MockSalesOrderRepositoryMockRecorder is the mock recorder for MockSalesOrderRepository.
type MockSalesOrderRepositoryMockRecorder struct {
	mock *MockSalesOrderRepository
}

// NewMockSalesOrderRepository creates a new mock instance.
func NewMockSalesOrderRepository(ctrl *gomock.Controller) *MockSalesOrderRepository {
	mock := &MockSalesOrderRepository{ctrl: ctrl}
	mock.recorder = &MockSalesOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSalesOrderRepository) EXPECT() *MockSalesOrderRepositoryMockRecorder {
	return m.recorder
}

// CreateSalesOrder mocks base method.
func (m *MockSalesOrderRepository) CreateSalesOrder(ctx context.Context, salesOrder *entity.SalesOrder) (*entity.SalesOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSalesOrder", ctx, salesOrder)
	ret0, _ := ret[0].(*entity.SalesOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSalesOrder indicates an expected call of CreateSalesOrder.
func (mr *MockSalesOrderRepositoryMockRecorder) CreateSalesOrder(ctx, salesOrder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSalesOrder", reflect.TypeOf((*MockSalesOrderRepository)(nil).CreateSalesOrder), ctx, salesOrder)
}

// DeleteSalesOrder mocks base method.
func (m *MockSalesOrderRepository) DeleteSalesOrder(ctx context.Context, scope *entity.Scope, salesOrderID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSalesOrder", ctx, scope, salesOrderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSalesOrder indicates an expected call of DeleteSalesOrder.
func (mr *MockSalesOrderRepositoryMockRecorder) DeleteSalesOrder(ctx, scope, salesOrderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSalesOrder", reflect.TypeOf((*MockSalesOrderRepository)(nil).DeleteSalesOrder), ctx, scope, salesOrderID)
}

// GetSalesOrder mocks base method.
func (m *MockSalesOrderRepository) GetSalesOrder(ctx context.Context, scope *entity.Scope, salesOrderID int64) (*entity.SalesOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSalesOrder", ctx, scope, salesOrderID)
	ret0, _ := ret[0].(*entity.SalesOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSalesOrder indicates an expected call of GetSalesOrder.
func (mr *MockSalesOrderRepositoryMockRecorder) GetSalesOrder(ctx, scope, salesOrderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSalesOrder", reflect.TypeOf((*MockSalesOrderRepository)(nil).GetSalesOrder), ctx, scope, salesOrderID)
}

// GetSalesOrderByID mocks base method.
func (m *MockSalesOrderRepository) GetSalesOrderByID(ctx context.Context, salesOrderID int64) (*entity.SalesOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSalesOrderByID", ctx, salesOrderID)
	ret0, _ := ret[0].(*entity.SalesOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSalesOrderByID indicates an expected call of GetSalesOrderByID.
func (mr *MockSalesOrderRepositoryMockRecorder) GetSalesOrderByID(ctx, salesOrderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSalesOrderByID", reflect.TypeOf((*MockSalesOrderRepository)(nil).GetSalesOrderByID), ctx, salesOrderID)
}

// ListSalesOrders mocks base method.
func (m *MockSalesOrderRepository) ListSalesOrders(ctx context.Context, filter *entity.SalesOrderFilter) ([]*entity.SalesOrder, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSalesOrders", ctx, filter)
	ret0, _ := ret[0].([]*entity.SalesOrder)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListSalesOrders indicates an expected call of ListSalesOrders.
func (mr *MockSalesOrderRepositoryMockRecorder) ListSalesOrders(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSalesOrders", reflect.TypeOf((*MockSalesOrderRepository)(nil).ListSalesOrders), ctx, filter)
}

// UpdateSalesOrder mocks base method.
func (m *MockSalesOrderRepository) UpdateSalesOrder(ctx context.Context, salesOrder *entity.SalesOrder) (*entity.SalesOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSalesOrder", ctx, salesOrder)
	ret0, _ := ret[0].(*entity.SalesOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSalesOrder indicates an expected call of UpdateSalesOrder.
func (mr *MockSalesOrderRepositoryMockRecorder) UpdateSalesOrder(ctx, salesOrder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSalesOrder", reflect.TypeOf((*MockSalesOrderRepository)(nil).UpdateSalesOrder), ctx, salesOrder)
}
