SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `crm_customer` (
  `id` bigint unsigned NOT NULL COMMENT 'Primary Key ID',
  `tenant_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Tenant ID',
  `space_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Workspace ID',
  `customer_name` varchar(128) NOT NULL DEFAULT '' COMMENT 'Customer Name',
  `customer_code` varchar(64) DEFAULT NULL COMMENT 'Customer Code',
  `industry` varchar(128) DEFAULT NULL COMMENT 'Industry',
  `level` varchar(64) DEFAULT NULL COMMENT 'Customer Level',
  `owner_user_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Owner User ID',
  `owner_user_name` varchar(128) NOT NULL DEFAULT '' COMMENT 'Owner User Name',
  `status` varchar(32) NOT NULL DEFAULT 'active' COMMENT 'Business Status',
  `mobile` varchar(32) DEFAULT NULL COMMENT 'Mobile',
  `email` varchar(128) DEFAULT NULL COMMENT 'Email',
  `address` varchar(512) DEFAULT NULL COMMENT 'Address',
  `remark` text COMMENT 'Remark',
  `created_by` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Created By',
  `updated_by` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Updated By',
  `created_at` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Create Time in Milliseconds',
  `updated_at` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Update Time in Milliseconds',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Soft Delete Flag',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_is_deleted` (`tenant_id`,`is_deleted`),
  KEY `idx_tenant_space_deleted` (`tenant_id`,`space_id`,`is_deleted`),
  KEY `idx_owner_user_id` (`owner_user_id`),
  KEY `idx_status` (`status`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_customer_code` (`customer_code`),
  KEY `idx_customer_name` (`customer_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='CRM customer master data';

CREATE TABLE IF NOT EXISTS `crm_contact` (
  `id` bigint unsigned NOT NULL COMMENT 'Primary Key ID',
  `tenant_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Tenant ID',
  `space_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Workspace ID',
  `customer_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Customer ID',
  `contact_name` varchar(128) NOT NULL DEFAULT '' COMMENT 'Contact Name',
  `mobile` varchar(32) DEFAULT NULL COMMENT 'Mobile',
  `email` varchar(128) DEFAULT NULL COMMENT 'Email',
  `title` varchar(128) DEFAULT NULL COMMENT 'Job Title',
  `is_primary` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Primary Contact Flag',
  `status` varchar(32) NOT NULL DEFAULT 'active' COMMENT 'Business Status',
  `remark` text COMMENT 'Remark',
  `created_by` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Created By',
  `updated_by` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Updated By',
  `created_at` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Create Time in Milliseconds',
  `updated_at` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Update Time in Milliseconds',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Soft Delete Flag',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_is_deleted` (`tenant_id`,`is_deleted`),
  KEY `idx_tenant_space_deleted` (`tenant_id`,`space_id`,`is_deleted`),
  KEY `idx_customer_id` (`customer_id`),
  KEY `idx_status` (`status`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_contact_name` (`contact_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='CRM customer contact data';

CREATE TABLE IF NOT EXISTS `crm_opportunity` (
  `id` bigint unsigned NOT NULL COMMENT 'Primary Key ID',
  `tenant_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Tenant ID',
  `space_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Workspace ID',
  `customer_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Customer ID',
  `opportunity_name` varchar(128) NOT NULL DEFAULT '' COMMENT 'Opportunity Name',
  `stage` varchar(64) NOT NULL DEFAULT 'initial' COMMENT 'Opportunity Stage',
  `amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT 'Opportunity Amount',
  `expected_close_date` date DEFAULT NULL COMMENT 'Expected Close Date',
  `owner_user_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Owner User ID',
  `owner_user_name` varchar(128) NOT NULL DEFAULT '' COMMENT 'Owner User Name',
  `status` varchar(32) NOT NULL DEFAULT 'open' COMMENT 'Business Status',
  `remark` text COMMENT 'Remark',
  `created_by` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Created By',
  `updated_by` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Updated By',
  `created_at` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Create Time in Milliseconds',
  `updated_at` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Update Time in Milliseconds',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Soft Delete Flag',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_is_deleted` (`tenant_id`,`is_deleted`),
  KEY `idx_tenant_space_deleted` (`tenant_id`,`space_id`,`is_deleted`),
  KEY `idx_customer_id` (`customer_id`),
  KEY `idx_owner_user_id` (`owner_user_id`),
  KEY `idx_status` (`status`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_stage` (`stage`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='CRM sales opportunity data';

CREATE TABLE IF NOT EXISTS `crm_follow_record` (
  `id` bigint unsigned NOT NULL COMMENT 'Primary Key ID',
  `tenant_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Tenant ID',
  `space_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Workspace ID',
  `customer_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Customer ID',
  `contact_id` bigint unsigned DEFAULT NULL COMMENT 'Contact ID',
  `follow_type` varchar(64) NOT NULL DEFAULT '' COMMENT 'Follow Type',
  `content` text NOT NULL COMMENT 'Follow Content',
  `next_follow_time` datetime(3) DEFAULT NULL COMMENT 'Next Follow Time',
  `owner_user_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Owner User ID',
  `owner_user_name` varchar(128) NOT NULL DEFAULT '' COMMENT 'Owner User Name',
  `status` varchar(32) NOT NULL DEFAULT 'active' COMMENT 'Business Status',
  `created_by` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Created By',
  `updated_by` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Updated By',
  `created_at` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Create Time in Milliseconds',
  `updated_at` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Update Time in Milliseconds',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Soft Delete Flag',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_is_deleted` (`tenant_id`,`is_deleted`),
  KEY `idx_tenant_space_deleted` (`tenant_id`,`space_id`,`is_deleted`),
  KEY `idx_customer_id` (`customer_id`),
  KEY `idx_contact_id` (`contact_id`),
  KEY `idx_owner_user_id` (`owner_user_id`),
  KEY `idx_status` (`status`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_next_follow_time` (`next_follow_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='CRM follow-up record data';

CREATE TABLE IF NOT EXISTS `crm_product` (
  `id` bigint unsigned NOT NULL COMMENT 'Primary Key ID',
  `tenant_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Tenant ID',
  `space_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Workspace ID',
  `product_name` varchar(128) NOT NULL DEFAULT '' COMMENT 'Product Name',
  `product_code` varchar(64) DEFAULT NULL COMMENT 'Product Code',
  `category` varchar(128) DEFAULT NULL COMMENT 'Product Category',
  `unit_price` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT 'Unit Price',
  `status` varchar(32) NOT NULL DEFAULT 'active' COMMENT 'Business Status',
  `remark` text COMMENT 'Remark',
  `created_by` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Created By',
  `updated_by` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Updated By',
  `created_at` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Create Time in Milliseconds',
  `updated_at` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Update Time in Milliseconds',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Soft Delete Flag',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_is_deleted` (`tenant_id`,`is_deleted`),
  KEY `idx_tenant_space_deleted` (`tenant_id`,`space_id`,`is_deleted`),
  KEY `idx_status` (`status`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_product_code` (`product_code`),
  KEY `idx_product_name` (`product_name`),
  KEY `idx_category` (`category`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='CRM product master data';

CREATE TABLE IF NOT EXISTS `crm_sales_order` (
  `id` bigint unsigned NOT NULL COMMENT 'Primary Key ID',
  `tenant_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Tenant ID',
  `space_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Workspace ID',
  `customer_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Customer ID',
  `opportunity_id` bigint unsigned DEFAULT NULL COMMENT 'Opportunity ID',
  `product_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Product ID',
  `product_name` varchar(128) NOT NULL DEFAULT '' COMMENT 'Product Snapshot Name',
  `sales_user_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Sales User ID',
  `sales_user_name` varchar(128) NOT NULL DEFAULT '' COMMENT 'Sales User Name',
  `quantity` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT 'Sales Quantity',
  `amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT 'Sales Amount',
  `order_date` date DEFAULT NULL COMMENT 'Order Date',
  `status` varchar(32) NOT NULL DEFAULT 'draft' COMMENT 'Business Status',
  `remark` text COMMENT 'Remark',
  `created_by` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Created By',
  `updated_by` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Updated By',
  `created_at` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Create Time in Milliseconds',
  `updated_at` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Update Time in Milliseconds',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Soft Delete Flag',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_is_deleted` (`tenant_id`,`is_deleted`),
  KEY `idx_tenant_space_deleted` (`tenant_id`,`space_id`,`is_deleted`),
  KEY `idx_customer_id` (`customer_id`),
  KEY `idx_opportunity_id` (`opportunity_id`),
  KEY `idx_product_id` (`product_id`),
  KEY `idx_sales_user_id` (`sales_user_id`),
  KEY `idx_status` (`status`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_order_date` (`order_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='CRM sales order data';

CREATE TABLE IF NOT EXISTS `crm_audit_log` (
  `id` bigint unsigned NOT NULL COMMENT 'Audit Log ID',
  `tenant_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Tenant ID',
  `space_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Workspace ID',
  `resource_type` varchar(64) NOT NULL DEFAULT '' COMMENT 'Resource Type',
  `resource_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Resource ID',
  `action` varchar(32) NOT NULL DEFAULT '' COMMENT 'Action Type',
  `operator_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Operator User ID',
  `before_snapshot` mediumtext COMMENT 'Before Snapshot JSON',
  `after_snapshot` mediumtext COMMENT 'After Snapshot JSON',
  `operation_at` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Operation Time in Milliseconds',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_space_operation_at` (`tenant_id`,`space_id`,`operation_at`),
  KEY `idx_resource` (`resource_type`,`resource_id`),
  KEY `idx_operator_id` (`operator_id`),
  KEY `idx_action` (`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='CRM audit log';
