/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by hertz generator.

package coze

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"

	im "github.com/coze-dev/coze-studio/backend/api/model/im"
	imApp "github.com/coze-dev/coze-studio/backend/application/im"
	imEntity "github.com/coze-dev/coze-studio/backend/domain/im/entity"
)

// ListIMPlatforms .
// @router /api/im/platforms [GET]
func ListIMPlatforms(ctx context.Context, c *app.RequestContext) {
	var req im.ListIMPlatformsRequest
	if err := c.BindAndValidate(&req); err != nil {
		invalidParamRequestResponse(c, err.Error())
		return
	}

	platforms, err := imApp.IMSVC.ListPlatformInfo(ctx)
	if err != nil {
		internalServerErrorResponse(ctx, c, err)
		return
	}

	resp := &im.ListIMPlatformsResponse{
		Code: 0,
		Msg:  "success",
		Data: make([]*im.IMPlatformInfo, 0, len(platforms)),
	}
	for _, platform := range platforms {
		resp.Data = append(resp.Data, &im.IMPlatformInfo{
			Platform:     string(platform.Platform),
			Name:         platform.Name,
			ConnectorID:  platform.ConnectorID,
			CallbackPath: platform.CallbackPath,
			CallbackURL:  platform.CallbackURL,
			Enabled:      platform.Enabled,
		})
	}

	c.JSON(consts.StatusOK, resp)
}

// FeishuEvent .
// @router /api/im/feishu/event [POST]
func FeishuEvent(ctx context.Context, c *app.RequestContext) {
	var req im.FeishuEventRequest
	if err := c.BindAndValidate(&req); err != nil {
		invalidParamRequestResponse(c, err.Error())
		return
	}

	resp := imApp.IMSVC.HandleFeishuEvent(ctx, &imEntity.CallbackRequest{
		Platform: imEntity.PlatformFeishu,
		Method:   string(c.Method()),
		Headers:  collectRequestHeaders(c),
		Query:    collectRequestQuery(c),
		Body:     append([]byte(nil), c.Request.Body()...),
	})
	if resp == nil {
		resp = imEntity.TextResponse(consts.StatusOK, "")
	}

	writeRawResponse(c, resp)
}

// DingTalkEvent .
// @router /api/im/dingtalk/event [GET]
func DingTalkEvent(ctx context.Context, c *app.RequestContext) {
	var req im.DingTalkEventRequest
	if err := c.BindAndValidate(&req); err != nil {
		invalidParamRequestResponse(c, err.Error())
		return
	}

	resp := imApp.IMSVC.HandleDingTalkEvent(ctx, &imEntity.CallbackRequest{
		Platform: imEntity.PlatformDingTalk,
		Method:   string(c.Method()),
		Headers:  collectRequestHeaders(c),
		Query:    collectRequestQuery(c),
		Body:     append([]byte(nil), c.Request.Body()...),
	})
	if resp == nil {
		resp = imEntity.TextResponse(consts.StatusOK, "")
	}

	writeRawResponse(c, resp)
}

// WeComEvent .
// @router /api/im/wecom/event [GET]
func WeComEvent(ctx context.Context, c *app.RequestContext) {
	var req im.WeComEventRequest
	if err := c.BindAndValidate(&req); err != nil {
		invalidParamRequestResponse(c, err.Error())
		return
	}

	resp := imApp.IMSVC.HandleWeComEvent(ctx, &imEntity.CallbackRequest{
		Platform: imEntity.PlatformWeCom,
		Method:   string(c.Method()),
		Headers:  collectRequestHeaders(c),
		Query:    collectRequestQuery(c),
		Body:     append([]byte(nil), c.Request.Body()...),
	})
	if resp == nil {
		resp = imEntity.TextResponse(consts.StatusOK, "")
	}

	writeRawResponse(c, resp)
}

func writeRawResponse(c *app.RequestContext, resp *imEntity.RawResponse) {
	c.SetStatusCode(resp.StatusCode)
	if resp.ContentType != "" {
		c.SetContentType(resp.ContentType)
	}
	c.Response.SetBody(resp.Body)
}

func collectRequestHeaders(c *app.RequestContext) map[string]string {
	headers := make(map[string]string)
	c.Request.Header.VisitAll(func(key, value []byte) {
		headers[string(key)] = string(value)
	})

	return headers
}

func collectRequestQuery(c *app.RequestContext) map[string]string {
	query := make(map[string]string)
	c.Request.URI().QueryArgs().VisitAll(func(key, value []byte) {
		query[string(key)] = string(value)
	})

	return query
}
